// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/status": {
            "get": {
                "summary": "Status",
                "operationId": "status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/certificate/cn": {
            "get": {
                "summary": "Common Name from Certificate",
                "operationId": "get-cn-from-certificate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PEM Encoded Certificate",
                        "name": "X-Forwarded-Tls-Client-Cert",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Client CN",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/certificate/cn-regex": {
            "get": {
                "summary": "Regex'ed Common Name from Certificate",
                "operationId": "get-cn-from-certificate-regex",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PEM Encoded Certificate",
                        "name": "X-Forwarded-Tls-Client-Cert",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Client CN",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/certificate/dn": {
            "get": {
                "summary": "Distinguished Name from Certificate",
                "operationId": "get-dn-from-certificate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PEM Encoded Certificate",
                        "name": "X-Forwarded-Tls-Client-Cert",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Client DN",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Traefik-ForwardAuth-Certs",
	Description: "Parses certificate information from cert in Headers",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
